<a href="https://colab.research.google.com/github/Ayushpal2006/Pandas/blob/Main/pandas_tutorial_(6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
import pandas as pd

In [8]:
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
series = pd.Series(data, index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [135]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['c0','c1','c2'], index=['r0','r1','r2'])
print(df)

    c0  c1  c2
r0   1   2   3
r1   4   5   6
r2   7   8   9

In [12]:
df.columns

Index(['c0', 'c1', 'c2'], dtype='object')

In [13]:
df.shape

(3, 3)

In [14]:
df.size

9

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, r0 to r2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c0      3 non-null      int64
 1   c1      3 non-null      int64
 2   c2      3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [17]:
df.describe()

        c0   c1   c2
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [23]:
df.index

Index(['r0', 'r1', 'r2'], dtype='object')

In [24]:
obesity_data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/obesity_prediction (1).csv')

In [25]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [26]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [27]:
obesity_data.head(30)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I
20,Male,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0,2.0,no,Walking,Overweight_Level_II
21,Female,52.0,1.69,87.0,yes,yes,3.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
22,Female,22.0,1.65,60.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Automobile,Normal_Weight
23,Female,22.0,1.60,82.0,yes,yes,1.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
24,Male,21.0,1.85,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
25,Male,20.0,1.60,50.0,yes,no,2.0,4.0,Frequently,yes,2.0,no,3.0,2.0,no,Public_Transportation,Normal_Weight
26,Male,21.0,1.70,65.0,yes,yes,2.0,1.0,Frequently,no,2.0,no,1.0,2.0,Always,Walking,Normal_Weight
27,Female,23.0,1.60,52.0,no,yes,2.0,4.0,Frequently,no,2.0,no,2.0,1.0,Sometimes,Automobile,Normal_Weight
28,Male,19.0,1.75,76.0,yes,yes,3.0,3.0,Sometimes,no,2.0,yes,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
29,Male,23.0,1.68,70.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,2.0,Frequently,Walking,Normal_Weight

In [28]:
obesity_data.tail(15)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2096,Female,25.955014,1.626449,104.879602,yes,yes,3.0,3.0,Sometimes,no,2.094901,no,0.070890,0.599441,Sometimes,Public_Transportation,Obesity_Type_III
2097,Female,25.996716,1.626580,105.037203,yes,yes,3.0,3.0,Sometimes,no,2.347322,no,0.008013,0.503896,Sometimes,Public_Transportation,Obesity_Type_III
2098,Female,25.992348,1.606474,104.954291,yes,yes,3.0,3.0,Sometimes,no,2.331123,no,0.063383,0.561661,Sometimes,Public_Transportation,Obesity_Type_III
2099,Female,25.974446,1.628855,108.090006,yes,yes,3.0,3.0,Sometimes,no,1.757105,no,0.085119,0.465444,Sometimes,Public_Transportation,Obesity_Type_III
2100,Female,25.777565,1.628205,107.378702,yes,yes,3.0,3.0,Sometimes,no,2.506631,no,0.025787,0.484165,Sometimes,Public_Transportation,Obesity_Type_III
2101,Female,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III
2102,Female,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III
2104,Female,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III
2105,Female,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [29]:
obesity_data.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2092,Female,26.0,1.626483,111.357062,yes,yes,3.0,3.0,Sometimes,no,2.61939,no,0.0,0.171034,Sometimes,Public_Transportation,Obesity_Type_III

In [30]:
obesity_data.sample(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1414,Female,38.445148,1.556028,77.684229,yes,yes,2.000000,3.000000,Sometimes,no,1.440629,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
21,Female,52.000000,1.690000,87.000000,yes,yes,3.000000,1.000000,Sometimes,yes,2.000000,no,0.000000,0.000000,no,Automobile,Obesity_Type_I
1636,Male,26.607478,1.793174,118.165082,yes,yes,2.002076,3.000000,Sometimes,no,2.338373,no,0.897562,0.081156,Sometimes,Public_Transportation,Obesity_Type_II
646,Female,22.033129,1.704223,51.437985,yes,yes,2.984425,3.000000,Frequently,no,2.044694,no,2.008256,1.250871,no,Public_Transportation,Insufficient_Weight
1826,Female,18.112503,1.827730,152.720545,yes,yes,3.000000,3.000000,Sometimes,no,2.154949,no,1.999897,0.957463,Sometimes,Public_Transportation,Obesity_Type_III
1089,Male,34.970367,1.713348,84.722222,yes,yes,2.884212,3.000000,Sometimes,no,3.000000,no,2.000000,0.832400,no,Automobile,Overweight_Level_II
1789,Male,22.906886,1.819550,120.775439,yes,yes,2.636719,2.806341,Sometimes,no,1.967591,no,1.525384,0.315595,Sometimes,Public_Transportation,Obesity_Type_II
308,Male,20.000000,1.800000,75.000000,no,yes,3.000000,4.000000,Always,no,3.000000,no,2.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
1577,Male,26.490926,1.872517,120.898397,yes,yes,2.443538,3.000000,Sometimes,no,2.939492,no,1.208142,0.738935,Sometimes,Public_Transportation,Obesity_Type_II
1155,Female,23.586058,1.700499,81.108599,yes,yes,2.042762,2.977400,Sometimes,no,1.522426,no,0.501417,1.029135,Sometimes,Public_Transportation,Overweight_Level_II

In [31]:
obesity_data.sample(10, random_state=29)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
631,Female,19.272573,1.713670,50.000000,no,yes,1.005578,4.000000,Frequently,no,1.000000,no,1.683957,0.704978,Sometimes,Public_Transportation,Insufficient_Weight
1216,Female,42.316070,1.583943,81.936398,yes,yes,2.490507,2.974204,Sometimes,no,1.846754,no,0.000000,0.000000,no,Automobile,Obesity_Type_I
1321,Female,23.000000,1.608469,82.954796,yes,yes,2.150054,2.988539,Sometimes,no,2.768325,no,2.085150,0.000000,no,Public_Transportation,Obesity_Type_I
1844,Female,26.000000,1.618573,104.928643,yes,yes,3.000000,3.000000,Sometimes,no,1.698767,no,0.000000,0.543960,Sometimes,Public_Transportation,Obesity_Type_III
820,Female,32.997118,1.672446,74.812707,yes,yes,2.948425,1.198643,Sometimes,no,1.000000,no,0.000000,0.173796,Sometimes,Automobile,Overweight_Level_I
2026,Female,21.838323,1.758959,137.792990,yes,yes,3.000000,3.000000,Sometimes,no,2.640539,no,1.879818,0.885993,Sometimes,Public_Transportation,Obesity_Type_III
692,Male,18.000000,1.767058,51.132809,yes,yes,2.708965,3.000000,Sometimes,no,1.873004,no,1.217180,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
454,Female,20.000000,1.680000,68.000000,no,yes,3.000000,1.000000,Sometimes,no,1.000000,no,1.000000,0.000000,no,Public_Transportation,Normal_Weight
875,Female,16.865984,1.644053,67.439589,yes,yes,1.314150,1.068196,Sometimes,no,1.364957,yes,0.000000,0.057926,no,Public_Transportation,Overweight_Level_I
1522,Male,28.363149,1.793476,112.725005,yes,yes,1.991240,3.000000,Sometimes,no,2.000000,no,0.000000,0.292956,Sometimes,Public_Transportation,Obesity_Type_II

In [32]:
obesity_data.sample(10, random_state=53)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
965,Female,17.258130,1.600184,65.000000,yes,yes,2.749629,2.298612,Sometimes,no,2.000000,yes,0.547515,1.619473,Sometimes,Public_Transportation,Overweight_Level_I
766,Male,21.017383,1.752391,79.109637,yes,yes,3.000000,1.000000,Sometimes,no,2.000000,no,2.572230,0.000000,Sometimes,Automobile,Overweight_Level_I
1874,Female,24.449655,1.635062,113.277388,yes,yes,3.000000,3.000000,Sometimes,no,2.578038,no,0.165422,0.463196,Sometimes,Public_Transportation,Obesity_Type_III
2001,Female,20.924956,1.752531,133.618706,yes,yes,3.000000,3.000000,Sometimes,no,2.887659,no,1.480919,0.779641,Sometimes,Public_Transportation,Obesity_Type_III
1526,Male,31.457413,1.874070,128.867444,yes,yes,2.956297,3.000000,Sometimes,yes,1.275100,no,0.901924,1.875023,Sometimes,Automobile,Obesity_Type_II
1364,Male,29.000000,1.666710,89.048151,yes,yes,1.897796,3.000000,Sometimes,no,1.193039,no,0.011519,0.000000,Sometimes,Automobile,Obesity_Type_I
1385,Female,42.586285,1.571417,81.918809,yes,yes,2.522183,1.326982,Sometimes,no,1.872673,no,1.048507,0.000000,no,Automobile,Obesity_Type_I
945,Male,23.455324,1.702516,75.000000,yes,yes,2.162519,3.000000,Sometimes,no,2.152666,no,1.078074,1.502839,Sometimes,Public_Transportation,Overweight_Level_I
123,Male,24.000000,1.660000,67.000000,yes,yes,3.000000,1.000000,Sometimes,no,2.000000,no,1.000000,0.000000,no,Public_Transportation,Normal_Weight
977,Male,21.180346,1.773766,89.282820,yes,yes,2.010684,1.322087,Sometimes,no,2.000000,no,0.540397,0.973834,Sometimes,Public_Transportation,Overweight_Level_II

In [33]:
obesity_data.columns.tolist()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [34]:
obesity_data.index

RangeIndex(start=0, stop=2111, step=1)

In [35]:
obesity_data.shape

(2111, 17)

In [37]:
obesity_data.size

35887

In [38]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [39]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [40]:
obesity_data.loc[0:10, 'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0
6,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
7,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0

In [41]:
obesity_data.loc[0:10]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I

In [42]:
obesity_data.loc[:, 'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000
1,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000
2,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000
3,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000
4,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269
2107,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390
2108,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209
2109,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107
2110,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452

In [43]:
obesity_data.loc[8:20, 'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0
11,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0
12,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0
13,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0
14,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0
15,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0
16,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0
17,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0
18,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0
19,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0
20,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0

In [44]:
obesity_data.loc[:20, 'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0
6,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
7,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0
11,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0
12,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0
13,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0
14,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0
15,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0
16,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0
17,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0
18,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0
19,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0
20,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0

In [45]:
obesity_data.loc[2100:, 'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
2100,25.777565,1.628205,107.378702,yes,yes,3.0,3.0,Sometimes,no,2.506631,no,0.025787
2101,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329
2102,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246
2103,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639
2104,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398
2105,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332
2106,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269
2107,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390
2108,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209
2109,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107
2110,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452

In [46]:
obesity_data.iloc[0:10, 0:5]

   Gender   Age  Height  Weight family_history
0  Female  21.0    1.62    64.0            yes
1  Female  21.0    1.52    56.0            yes
2    Male  23.0    1.80    77.0            yes
3    Male  27.0    1.80    87.0             no
4    Male  22.0    1.78    89.8             no
5    Male  29.0    1.62    53.0             no
6  Female  23.0    1.50    55.0            yes
7    Male  22.0    1.64    53.0             no
8    Male  24.0    1.78    64.0            yes
9    Male  22.0    1.72    68.0            yes

In [47]:
obesity_data.iloc[:, 0:5]

      Gender        Age    Height      Weight family_history
0     Female  21.000000  1.620000   64.000000            yes
1     Female  21.000000  1.520000   56.000000            yes
2       Male  23.000000  1.800000   77.000000            yes
3       Male  27.000000  1.800000   87.000000             no
4       Male  22.000000  1.780000   89.800000             no
...      ...        ...       ...         ...            ...
2106  Female  20.976842  1.710730  131.408528            yes
2107  Female  21.982942  1.748584  133.742943            yes
2108  Female  22.524036  1.752206  133.689352            yes
2109  Female  24.361936  1.739450  133.346641            yes
2110  Female  23.664709  1.738836  133.472641            yes

[2111 rows x 5 columns]

In [48]:
obesity_data.iloc[0:10]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [49]:
obesity_data.iloc[[10, 20, 30], [0,1,2]]

   Gender   Age  Height
10   Male  26.0    1.85
20   Male  22.0    1.65
30   Male  29.0    1.77

In [51]:
obesity_data.at[0, 'Age']

np.float64(21.0)

In [52]:
obesity_data.iat[0, 5]

'no'

In [53]:
obesity_data[['Age', 'Height', 'Weight']]

            Age    Height      Weight
0     21.000000  1.620000   64.000000
1     21.000000  1.520000   56.000000
2     23.000000  1.800000   77.000000
3     27.000000  1.800000   87.000000
4     22.000000  1.780000   89.800000
...         ...       ...         ...
2106  20.976842  1.710730  131.408528
2107  21.982942  1.748584  133.742943
2108  22.524036  1.752206  133.689352
2109  24.361936  1.739450  133.346641
2110  23.664709  1.738836  133.472641

[2111 rows x 3 columns]

In [54]:
obesity_data.Age

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [55]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I

In [56]:
obesity_data.loc[obesity_data['Height']>1]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [57]:
obesity_data.loc[obesity_data['Weight']<50]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.000000,1.560000,49.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,yes,2.000000,0.000000,no,Walking,Normal_Weight
37,Female,21.000000,1.600000,48.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,1.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.000000,1.500000,44.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
60,Female,21.000000,1.550000,49.000000,yes,yes,2.000000,3.000000,Sometimes,no,3.000000,no,3.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
75,Female,23.000000,1.630000,45.000000,yes,no,3.000000,3.000000,Sometimes,no,3.000000,yes,2.000000,0.000000,no,Public_Transportation,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [58]:
obesity_data.loc[(obesity_data['Weight']<50) & (obesity_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.0,1.56,49.0,no,yes,2.0,3.0,Sometimes,no,1.0,yes,2.0,0.0,no,Walking,Normal_Weight
37,Female,21.0,1.60,48.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.0,1.50,44.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
60,Female,21.0,1.55,49.0,yes,yes,2.0,3.0,Sometimes,no,3.0,no,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
94,Female,24.0,1.60,48.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
113,Female,22.0,1.50,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Walking,Normal_Weight
156,Female,35.0,1.53,45.0,yes,no,3.0,3.0,Frequently,no,1.0,no,0.0,1.0,no,Automobile,Normal_Weight
176,Female,18.0,1.57,48.0,yes,yes,3.0,1.0,Always,no,1.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
180,Female,18.0,1.58,48.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
218,Female,21.0,1.50,42.3,yes,no,1.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Public_Transportation,Normal_Weight
234,Female,19.0,1.59,49.0,yes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
244,Female,21.0,1.54,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,yes,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
253,Female,26.0,1.59,47.0,yes,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
303,Female,16.0,1.57,49.0,no,yes,2.0,4.0,Always,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
307,Female,23.0,1.59,48.0,yes,yes,2.0,1.0,Frequently,no,1.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
318,Female,25.0,1.56,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
346,Female,21.0,1.54,47.0,yes,no,3.0,3.0,Always,no,1.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
359,Female,33.0,1.56,48.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
385,Female,16.0,1.55,45.0,no,yes,2.0,3.0,Frequently,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
445,Female,19.0,1.51,45.0,no,yes,2.0,4.0,Sometimes,no,1.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
457,Female,19.0,1.50,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [59]:
obesity_data.loc[(obesity_data['Weight']<50) | (obesity_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.000000,3.000000,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
5,Male,29.000000,1.620000,53.000000,no,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [60]:
obesity_data[obesity_data['Height']>1]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [61]:
obesity_data[(obesity_data['Weight']<50) | (obesity_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.000000,3.000000,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
5,Male,29.000000,1.620000,53.000000,no,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [62]:
obesity_data.loc[obesity_data['Obesity'].str.contains('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [63]:
obesity_data.loc[obesity_data['Obesity'].str.startswith('Weight')]

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity]
Index: []

In [64]:
obesity_data[obesity_data['Obesity'].str.contains('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [65]:
obesity_data[obesity_data['Obesity'].str.startswith('Weight')]

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity]
Index: []

In [68]:
obesity_data.loc[0,'Age']

np.float64(22.0)

In [69]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [70]:
obesity_data.loc[:, 'SMOKE'] = 'yes'

In [71]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [72]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [74]:
obesity_data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/obesity_prediction (1).csv')

In [75]:
obesity_data.loc[[2,3], 'Height'] = 1.6

In [76]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [77]:
obesity_data.loc[:2, 'SMOKE'] = 'may be'

In [78]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [79]:
obesity_data.iloc[1,4] = 'no data'

In [80]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [81]:
obesity_data.iloc[:,9] = 'doesnt matter'

In [82]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesnt matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,doesnt matter,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,doesnt matter,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,doesnt matter,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,doesnt matter,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,doesnt matter,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,doesnt matter,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,doesnt matter,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,doesnt matter,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,doesnt matter,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,doesnt matter,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I

In [85]:
obesity_data.at[2,'Obesity'] = 'Overrrr'

In [86]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesnt matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [87]:
obesity_data.iat[2,0] = 'Secret'

In [88]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesnt matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [89]:
obesity_data['SMOKE'] = 'yes'

In [90]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [91]:
def increment_age_by_5(x):
    return x+5

obesity_data['Age'] = obesity_data['Age'].apply(increment_age_by_5)

obesity_data['Age']

0       26.000000
1       26.000000
2       28.000000
3       32.000000
4       27.000000
          ...
2106    25.976842
2107    26.982942
2108    27.524036
2109    29.361936
2110    28.664709
Name: Age, Length: 2111, dtype: float64

In [92]:
obesity_data['Age'] = obesity_data['Age'].apply(lambda x : x - 5)
obesity_data['Age']

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [93]:
obesity_data['Age Category'] = obesity_data['Age'].apply(lambda x : 'Very Young' if x<25 else 'Not so young')

In [94]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so young
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Very Young
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,yes,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,yes,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,Not so young
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,yes,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not so young
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,yes,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not so young
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,Not so young
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not so young
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,Very Young

In [95]:
import numpy as np

obesity_data['New Age Category'] = np.where(obesity_data['Age'] < 25, 'Very Young', 'Not so young')

In [96]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so young,Not so young
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Very Young,Very Young
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,yes,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young,Very Young
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,yes,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,Not so young,Not so young
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,yes,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not so young,Not so young
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,yes,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not so young,Not so young
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,Not so young,Not so young
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not so young,Not so young
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,Very Young,Very Young

In [97]:
obesity_data.insert(2, 'BMI', 20)

In [98]:
obesity_data.head(20)

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,20,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,20,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,20,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,20,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,20,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young
5,Male,29.0,20,1.62,53.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so young,Not so young
6,Female,23.0,20,1.50,55.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Very Young,Very Young
7,Male,22.0,20,1.64,53.0,no,no,2.0,3.0,Sometimes,yes,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
8,Male,24.0,20,1.78,64.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young,Very Young
9,Male,22.0,20,1.72,68.0,yes,yes,2.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
10,Male,26.0,20,1.85,105.0,yes,yes,3.0,3.0,Frequently,yes,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,Not so young,Not so young
11,Female,21.0,20,1.72,80.0,yes,yes,2.0,3.0,Frequently,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young
12,Male,22.0,20,1.65,56.0,no,no,3.0,3.0,Sometimes,yes,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
13,Male,41.0,20,1.80,99.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not so young,Not so young
14,Male,23.0,20,1.77,60.0,yes,yes,3.0,1.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
15,Female,22.0,20,1.70,66.0,yes,no,3.0,3.0,Always,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
16,Male,27.0,20,1.93,102.0,yes,yes,2.0,1.0,Sometimes,yes,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not so young,Not so young
17,Female,29.0,20,1.53,78.0,no,yes,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,Not so young,Not so young
18,Female,30.0,20,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not so young,Not so young
19,Female,23.0,20,1.65,70.0,yes,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,Very Young,Very Young

In [99]:
obesity_data.drop(columns='BMI')

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,yes,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.000000,1.520000,56.000000,no data,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.000000,1.600000,77.000000,yes,no,2.0,3.0,Sometimes,yes,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.000000,1.600000,87.000000,no,no,3.0,3.0,Sometimes,yes,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,yes,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Very Young,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Very Young,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Very Young,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Very Young,Very Young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Very Young,Very Young

In [100]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,20,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,20,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,20,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,20,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,20,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [102]:
obesity_data.drop(columns='BMI', inplace=True)

KeyError: "['BMI'] not found in axis"

In [103]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [104]:
obesity_data.insert(2, 'BMI', obesity_data['Weight']/obesity_data['Height']**2)

In [105]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,24.238227,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,30.078125,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [106]:
obesity_data = obesity_data.drop(columns='BMI')

In [107]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [108]:
obesity_data.insert(2, 'BMI', obesity_data['Weight']/obesity_data['Height']**2)

In [109]:
obesity_data.insert(2, 'BMI new', obesity_data['Weight']/obesity_data['Height']**2)

In [110]:
obesity_data.head()

,Gender,Age,BMI new,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,...,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,24.386526,24.386526,1.62,64.0,yes,no,2.0,3.0,...,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,24.238227,24.238227,1.52,56.0,no data,no,3.0,3.0,...,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,30.078125,30.078125,1.60,77.0,yes,no,2.0,3.0,...,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,33.984375,33.984375,1.60,87.0,no,no,3.0,3.0,...,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,28.342381,28.342381,1.78,89.8,no,no,2.0,1.0,...,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [111]:
obesity_data.drop(columns=['BMI', 'BMI new'], inplace=True)

In [112]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [113]:
del obesity_data['CAEC']

In [115]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [118]:
obesity_data.rename(columns={'Obesity': 'Category', 'New Age Category' : 'reduntant info'}, inplace=True)

In [120]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category,reduntant info
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young,Very Young

In [121]:
del obesity_data['reduntant info']

In [123]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [136]:
df1 = pd.DataFrame({
    'id' : [1,2,3,4],
    'name' : ['Keerti', 'Amit', 'Educosys', 'YouTube']
})

df2 = pd.DataFrame({
    'id' : [3,4, 5, 6],
    'course' : ['GenAI', 'CPP', 'HLD', 'LLD']
})

inner_result = pd.merge(df1, df2, how='inner', on='id')
inner_result

   id      name course
0   3  Educosys  GenAI
1   4   YouTube    CPP

In [127]:
df1

   id      name
0   1    Keerti
1   2      Amit
2   3  Educosys
3   4   YouTube

In [137]:
outer_result = pd.merge(df1, df2, how='outer', on='id')
outer_result

   id      name course
0   1    Keerti    NaN
1   2      Amit    NaN
2   3  Educosys  GenAI
3   4   YouTube    CPP
4   5       NaN    HLD
5   6       NaN    LLD

In [138]:
left_result = pd.merge(df1, df2, how='left', on='id')
left_result

   id      name course
0   1    Keerti    NaN
1   2      Amit    NaN
2   3  Educosys  GenAI
3   4   YouTube    CPP

In [139]:
right_result = pd.merge(df1, df2, how='right', on='id')
right_result

   id      name course
0   3  Educosys  GenAI
1   4   YouTube    CPP
2   5       NaN    HLD
3   6       NaN    LLD

In [140]:
df3 = pd.DataFrame({
    'id1' : [1,2,3,4],
    'name' : ['Keerti', 'Amit', 'Educosys', 'YouTube']
})

df4 = pd.DataFrame({
    'id2' : [3,4, 5, 6],
    'course' : ['GenAI', 'CPP', 'HLD', 'LLD']
})

inner_result = pd.merge(df3, df4, how='inner', left_on='id1', right_on='id2')
inner_result

   id1      name  id2 course
0    3  Educosys    3  GenAI
1    4   YouTube    4    CPP

In [143]:
df1 = pd.DataFrame({
    'id' : [1,2,3,4],
    'name' : ['Keerti', 'Amit', 'Educosys', 'YouTube']
})

df2 = pd.DataFrame({
    'id' : [3,4, 5, 6],
    'course' : ['GenAI', 'CPP', 'HLD', 'LLD']
})

result = pd.concat([df1, df2], axis=0, ignore_index=True)
result

   id      name course
0   1    Keerti    NaN
1   2      Amit    NaN
2   3  Educosys    NaN
3   4   YouTube    NaN
4   3       NaN  GenAI
5   4       NaN    CPP
6   5       NaN    HLD
7   6       NaN    LLD

In [144]:
result2 = pd.concat([df1, df2], axis=1)
result2

   id      name  id course
0   1    Keerti   3  GenAI
1   2      Amit   4    CPP
2   3  Educosys   5    HLD
3   4   YouTube   6    LLD

In [145]:
result3 = pd.concat([df1, df2], axis=0, keys=['df1', 'df2'])
result3

       id      name course
df1 0   1    Keerti    NaN
    1   2      Amit    NaN
    2   3  Educosys    NaN
    3   4   YouTube    NaN
df2 0   3       NaN  GenAI
    1   4       NaN    CPP
    2   5       NaN    HLD
    3   6       NaN    LLD

In [146]:
result3.isna()

          id   name  course
df1 0  False  False    True
    1  False  False    True
    2  False  False    True
    3  False  False    True
df2 0  False   True   False
    1  False   True   False
    2  False   True   False
    3  False   True   False

In [147]:
result3.notna()

         id   name  course
df1 0  True   True   False
    1  True   True   False
    2  True   True   False
    3  True   True   False
df2 0  True  False    True
    1  True  False    True
    2  True  False    True
    3  True  False    True

In [148]:
result3.isna().sum()

id        0
name      4
course    4
dtype: int64

In [149]:
result3.notna().sum()

id        8
name      4
course    4
dtype: int64

In [150]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.0,1.60,77.0,yes,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [151]:
obesity_data.loc[0, 'Age'] = np.nan
obesity_data.loc[0, 'SMOKE'] = np.nan
obesity_data.loc[2, 'family_history'] = np.nan

In [152]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,NaN,1.62,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.0,1.60,77.0,NaN,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [153]:
obesity_data.fillna(0, inplace=True)

In [154]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,0.0,1.62,64.0,yes,no,2.0,3.0,0,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.0,1.60,77.0,0,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [155]:
obesity_data.loc[0, 'Age'] = np.nan
obesity_data.loc[0, 'SMOKE'] = np.nan
obesity_data.loc[2, 'family_history'] = np.nan
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,NaN,1.62,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.0,1.60,77.0,NaN,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [156]:
obesity_data['Age'] = obesity_data['Age'].fillna(obesity_data['Age'].mean())

In [157]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,24.31417,1.62,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.00000,1.60,77.0,NaN,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.00000,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.00000,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [158]:
obesity_data.fillna({'SMOKE': 'no', 'family_history': 'no'}, inplace=True)

In [159]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,24.31417,1.62,64.0,yes,no,2.0,3.0,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.00000,1.60,77.0,no,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,27.00000,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.00000,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [160]:
obesity_data.loc[3, 'Age'] = np.nan
obesity_data.loc[0, 'SMOKE'] = np.nan
obesity_data.loc[2, 'family_history'] = np.nan
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,24.31417,1.62,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.00000,1.60,77.0,NaN,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,NaN,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.00000,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [161]:
obesity_data['Age'] = obesity_data['Age'].fillna(obesity_data['Age'].interpolate())

In [162]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,24.31417,1.62,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Secret,23.00000,1.60,77.0,NaN,no,2.0,3.0,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrrr,Very Young
3,Male,22.50000,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.00000,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [163]:
obesity_data.dropna(inplace=True)

In [164]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
1,Female,21.0,1.52,56.0,no data,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
3,Male,22.5,1.60,87.0,no,no,3.0,3.0,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so young
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Very Young

In [165]:
obesity_data.dropna(axis = 1)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
1,Female,21.000000,1.520000,56.000000,no data,no,3.0,3.0,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Very Young
3,Male,22.500000,1.600000,87.000000,no,no,3.0,3.0,yes,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,yes,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
5,Male,29.000000,1.620000,53.000000,no,yes,2.0,3.0,yes,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight,Not so young
6,Female,23.000000,1.500000,55.000000,yes,yes,3.0,3.0,yes,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Very Young

In [168]:
obesity_data.groupby('Gender').count()

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
Gender,,,,,,,,,,,,,,,,
Female,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042
Male,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067

In [169]:
obesity_data.groupby('Gender')['Height'].mean()

Gender
Female    1.643320
Male      1.758464
Name: Height, dtype: float64

In [170]:
obesity_data.groupby('Gender')['Weight'].median()

Gender
Female    78.004194
Male      89.981680
Name: Weight, dtype: float64

In [171]:
obesity_data.groupby('Gender')['Weight'].agg(['sum', 'mean'])

                 sum       mean
Gender
Female  85777.365833  82.319929
Male    96864.802872  90.782383

In [172]:
obesity_data.groupby('Gender')['Weight']

In [174]:
obesity_data.groupby('Gender')['Weight'].sum()

Gender
Female    85777.365833
Male      96864.802872
Name: Weight, dtype: float64