# Pandas

In [63]:
import pandas as pd
import numpy as np

## Key Data Structure in Pandas 
* Series
* Data frame

In [4]:
s = pd.Series([1,2,3,4,5] , index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
df = pd.DataFrame({'name': ["Ayush" , "Aman" , "ksk"] , 'marks' : [100,99,98]})
df

    name  marks
0  Ayush    100
1   Aman     99
2    ksk     98

In [9]:
df  = pd.read_csv("iris.csv")
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [11]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [12]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [13]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

## Markdown

In [16]:
df["sepal.length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [17]:
type(df["sepal.length"])

pandas.core.series.Series

In [21]:
df[["sepal.length" , "sepal.width" ]]

     sepal.length  sepal.width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [22]:
df.iloc[0]

sepal.length       5.1
sepal.width        3.5
petal.length       1.4
petal.width        0.2
variety         Setosa
Name: 0, dtype: object

In [23]:
df2 = pd.read_csv("iris.csv")

In [24]:
df2

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          NaN           1.4          0.2     Setosa
2             NaN          3.2           1.3          0.2        NaN
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           NaN          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [25]:
df2.dropna()

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[147 rows x 5 columns]

In [26]:
df2.fillna(0 )

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          0.0           1.4          0.2     Setosa
2             0.0          3.2           1.3          0.2          0
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           0.0          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [27]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [28]:
df.rename(columns={"sepal.length": "SL"})

      SL  sepal.width  petal.length  petal.width    variety
0    5.1          3.5           1.4          0.2     Setosa
1    4.9          3.0           1.4          0.2     Setosa
2    4.7          3.2           1.3          0.2     Setosa
3    4.6          3.1           1.5          0.2     Setosa
4    5.0          3.6           1.4          0.2     Setosa
..   ...          ...           ...          ...        ...
145  6.7          3.0           5.2          2.3  Virginica
146  6.3          2.5           5.0          1.9  Virginica
147  6.5          3.0           5.2          2.0  Virginica
148  6.2          3.4           5.4          2.3  Virginica
149  5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [30]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [35]:
df['sepal.width'] = df['sepal.width'].astype(int)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    int32
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(3), int32(1), object(1)
memory usage: 5.4+ KB

In [37]:
len(df)

150

In [38]:
df["zeros"] = [0 for i in range(len(df))]

In [42]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety  zeros
0             5.1            3           1.4          0.2     Setosa      0
1             4.9            3           1.4          0.2     Setosa      0
2             4.7            3           1.3          0.2     Setosa      0
3             4.6            3           1.5          0.2     Setosa      0
4             5.0            3           1.4          0.2     Setosa      0
..            ...          ...           ...          ...        ...    ...
145           6.7            3           5.2          2.3  Virginica      0
146           6.3            2           5.0          1.9  Virginica      0
147           6.5            3           5.2          2.0  Virginica      0
148           6.2            3           5.4          2.3  Virginica      0
149           5.9            3           5.1          1.8  Virginica      0

[150 rows x 6 columns]

In [43]:
def fx(a):
    return a+1 
df["zeros + 1"] = df["zeros"].apply(fx)

In [44]:
df

,sepal.length,sepal.width,petal.length,petal.width,variety,zeros,zeros + 1
0,5.1,3,1.4,0.2,Setosa,0,1
1,4.9,3,1.4,0.2,Setosa,0,1
2,4.7,3,1.3,0.2,Setosa,0,1
3,4.6,3,1.5,0.2,Setosa,0,1
4,5.0,3,1.4,0.2,Setosa,0,1
...,...,...,...,...,...,...,...
145,6.7,3,5.2,2.3,Virginica,0,1
146,6.3,2,5.0,1.9,Virginica,0,1
147,6.5,3,5.2,2.0,Virginica,0,1
148,6.2,3,5.4,2.3,Virginica,0,1
149,5.9,3,5.1,1.8,Virginica,0,1

In [45]:
df.to_csv("export.csv" , index=False )

In [46]:
df1 = pd.DataFrame({
    'name' : ['Ayush' , 'khushi' , 'shena'],
    'marks' : [100,97,95]
})

In [47]:
df1

     name  marks
0   Ayush    100
1  khushi     97
2   shena     95

In [48]:
df2 = pd.DataFrame({
    'name' : ['ayushi' , 'chootu' , 'sakshi' , 'mahiiii'],
    'marks' : [100,97,10,5]
})

In [49]:
df2

      name  marks
0   ayushi    100
1   chootu     97
2   sakshi     10
3  mahiiii      5

In [50]:
pd.concat([df1 ,df2])

      name  marks
0    Ayush    100
1   khushi     97
2    shena     95
0   ayushi    100
1   chootu     97
2   sakshi     10
3  mahiiii      5

In [51]:
df1 = pd.DataFrame({
    'name' : ['Ayush' , 'khushi' , 'shena'],
    'marks' : [87,67,95]
})

In [52]:
df2 = pd.DataFrame({
    'name' : ['Ayush' , 'khushi' , 'shena'],
    'Roll No' : [1,2,3]
})

In [53]:
df2

     name  Roll No
0   Ayush        1
1  khushi        2
2   shena        3

In [54]:
pd.merge(df1,df2 , on="name")

     name  marks  Roll No
0   Ayush     87        1
1  khushi     67        2
2   shena     95        3

In [62]:
dates = pd.date_range('2023-01-01', periods=100, freq='D')
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
               '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
               '2023-03-02', '2023-03-03', '2023-03-04', '2023-03-05',
               '2023-03-06', '2023-03-07', '2023-03-08', '2023-03-09',
               '2023-03-10', '2023-03-11', '2023-03-12', '2023-03-13',
               '2023-03-14', '2023-03-15', '2023-03-16', '2023-03-17',
               '2023-03-18', '2023-03-19', '2023-03-20', '2023-03-21',
               '2023-03-22', '2023-03-23', '2023-03-24', '2023-03-25',
               '2023-03-26', '2023-03-27', '2023-03-28', '2023-03-29',
               '2023-03-30', '2023-03-31', '2023-04-01', '2023-04-02',
               '2023-04-03', '2023-04-04', '2023-04-05', '2023-04-06',
               '2023-04-07', '2023-04-08', '2023-04-09', '2023-04-10'],
              dtype='datetime64[ns]', freq='D')

In [77]:
df = pd.DataFrame(np.random.rand(344,5))
df

            0         1         2         3         4
0    0.836585  0.888090  0.657612  0.983800  0.832459
1    0.848265  0.066229  0.384072  0.631272  0.609856
2    0.678301  0.252675  0.841170  0.748519  0.714969
3    0.043992  0.353802  0.197681  0.830539  0.944702
4    0.399727  0.192897  0.629608  0.252172  0.100473
..        ...       ...       ...       ...       ...
339  0.587986  0.813756  0.149269  0.518638  0.455562
340  0.490771  0.147140  0.247478  0.400830  0.130358
341  0.952465  0.255755  0.432281  0.360327  0.580253
342  0.094861  0.718368  0.242678  0.564838  0.454936
343  0.960984  0.726593  0.296970  0.581729  0.420635

[344 rows x 5 columns]

In [84]:
df  = pd.DataFrame(np.random.randint(0, 100, size=(344, 5)) , index=np.arange(344))
df

      0   1   2   3   4
0    40  91   4   1  86
1    22  24  31  86  18
2    70  57  72  17  71
3    80  50  16  10  19
4    61  55  51  44  35
..   ..  ..  ..  ..  ..
339  92  28  93  73  88
340  69  37   4  35  16
341  38  75   6  63  68
342  21  25  92  83  31
343  71  10  30  56  67

[344 rows x 5 columns]

In [85]:
df.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       334, 335, 336, 337, 338, 339, 340, 341, 342, 343],
      dtype='int32', length=344)

In [86]:
df.columns

RangeIndex(start=0, stop=5, step=1)

In [87]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,334,335,336,337,338,339,340,341,342,343
0,40,22,70,80,61,94,24,80,33,37,...,52,90,58,87,5,92,69,38,21,71
1,91,24,57,50,55,96,80,80,49,38,...,42,76,73,83,24,28,37,75,25,10
2,4,31,72,16,51,61,42,24,45,61,...,5,72,26,48,87,93,4,6,92,30
3,1,86,17,10,44,59,91,73,78,79,...,48,9,75,70,25,73,35,63,83,56
4,86,18,71,19,35,88,38,66,46,83,...,7,94,12,67,60,88,16,68,31,67

In [93]:
df.loc[0,0] = 50

In [94]:
df.head()

    0   1   2   3   4
0  50  91   4   1  86
1  22  24  31  86  18
2  70  57  72  17  71
3  80  50  16  10  19
4  61  55  51  44  35

In [104]:
df.columns = list("ABCDE")

In [105]:
df.head()

    A   B   C   D   E
0  50  91   4   1  86
1  22  24  31  86  18
2  70  57  72  17  71
3  80  50  16  10  19
4  61  55  51  44  35

In [106]:
df.loc[0,0] = 645

In [107]:
df

      A   B   C   D   E      0
0    50  91   4   1  86  645.0
1    22  24  31  86  18    NaN
2    70  57  72  17  71    NaN
3    80  50  16  10  19    NaN
4    61  55  51  44  35    NaN
..   ..  ..  ..  ..  ..    ...
339  92  28  93  73  88    NaN
340  69  37   4  35  16    NaN
341  38  75   6  63  68    NaN
342  21  25  92  83  31    NaN
343  71  10  30  56  67    NaN

[344 rows x 6 columns]

In [108]:
df.loc[0,"A"] = 50000

In [110]:
df.head()

       A   B   C   D   E      0
0  50000  91   4   1  86  645.0
1     22  24  31  86  18    NaN
2     70  57  72  17  71    NaN
3     80  50  16  10  19    NaN
4     61  55  51  44  35    NaN

In [117]:
# df.dropna(axis=1)
df.drop(0,axis=1)

         A   B   C   D   E
0    50000  91   4   1  86
1       22  24  31  86  18
2       70  57  72  17  71
3       80  50  16  10  19
4       61  55  51  44  35
..     ...  ..  ..  ..  ..
339     92  28  93  73  88
340     69  37   4  35  16
341     38  75   6  63  68
342     21  25  92  83  31
343     71  10  30  56  67

[344 rows x 5 columns]

In [119]:
df.loc[[1,2],['C','D']]

    C   D
1  31  86
2  72  17

In [121]:
df.loc[(df["A"]<5) & (df["C"] > 5)]

     A   B   C   D   E   0
12   4  29  44  25  69 NaN
52   4  88  30  69  85 NaN
57   3  42  68  74  56 NaN
58   0  54  49  27  69 NaN
82   0  24  34  21  44 NaN
85   3  53  26  43  60 NaN
100  0  70  48   8  37 NaN
126  4   7   6  71  44 NaN
137  3  20  94  50  64 NaN
166  3  76  70  69  49 NaN
181  3  70  97   3  54 NaN
213  0  90  68  14  15 NaN
214  0  19  22  73  33 NaN
233  1  40  48  16  11 NaN
262  0  18  37  86  34 NaN
293  2  88  78  21  69 NaN
304  0  30  86  81  21 NaN
307  1  93  14  92  49 NaN
309  2  17  91  21  57 NaN
318  4  90  48  88   8 NaN
333  1   2  60  49  42 NaN